const mongoose = require('mongoose')
const teacher = mongoose.Schema({
  'teacherID':String,
  'name':String,
  'subject': String,
  'grade1': String, 
  'grade2': String,
  'grade3': String,
  'grade4': String,
  'grade5': String,
  'grade6': String,
  'grade7': String,
  'grade8': String,
  'place1': String,
  'place2': String,
  'place3': String,
  'place4': String,
  'place5': String,
  'place6': String,
  'place7': String,
  'place8': String,
  'place9': String,
  'place10': String,
  'time1': String,
  'time2': String,
  'time3': String,
  'time4': String,
  'time5': String,
  'time6': String,
  'time7': String,
  'time8': String,
  'time9': String,
  'time10': String,
  'time11': String,
  'time12': String,
  'time13': String,
  'buoi1':String,
  'buoi2':String,
  'buoi3':String,
  'buoi4':String,
  'buoi5':String,
  'buoi6':String,
  'buoi7':String,
  'buoi8':String,
  'buoi9':String,
  'buoi10':String,
  'buoi11':String,
  'buoi12':String,
  'buoi13':String,
  'buoi14':String,
  'buoi15':String,
  'buoi16':String,
  'buoi17':String,
  'buoi18':String,
  'buoi19':String,
  'buoi20':String,
  'buoi21':String,
  'buoi22':String,
  'buoi23':String,
  'buoi24':String,
  'buoi25':String,
  'buoi26':String,
  'buoi27':String,
  'buoi28':String,
  'buoi29':String,
  'buoi30':String,
  'buoi31':String,
  'buoi32':String,
  'buoi33':String,
  'buoi34':String,
  'buoi35':String,
  'buoi36':String,
  'buoi37':String,
  'buoi38':String,
  'buoi39':String,
  'buoi40':String,
  'buoi41':String,
  'buoi42':String,
  'buoi43':String,
  'buoi44':String,
  'buoi45':String,
  'buoi46':String,
  'buoi47':String,
  'buoi48':String,
  'buoi49':String,
  'buoi50':String,
  'buoi51':String,
  'buoi52':String,
  'buoi53':String,
  'buoi54':String,
  'buoi55':String,
  'buoi56':String,
  'buoi57':String,
  'buoi58':String,
  'buoi59':String,
  'buoi60':String,
  'buoi61':String,
  'buoi62':String,
  'buoi63':String,
  'buoi64':String,
  'buoi65':String,
  'buoi66':String,
  'buoi67':String,
  'buoi68':String,
  'buoi69':String,
  'buoi70':String,
  'buoi71':String,
  'buoi72':String,
  'buoi73':String,
  'buoi74':String,
  'buoi75':String,
  'buoi76':String,
  'buoi77':String,
  'buoi78':String,
  'buoi79':String,
  'buoi80':String,
  'buoi81':String,
  'buoi82':String,
  'buoi83':String,
  'buoi84':String,
  'buoi85':String,
  'buoi86':String,
  'buoi87':String,
  'buoi88':String,
  'buoi89':String,
  'buoi90':String,
  'buoi91':String,
  'buoi92':String,
  'buoi93':String,
  'buoi94':String,
  'buoi95':String,
  'buoi96':String,
  'buoi97':String,
  'buoi98':String,
  'buoi99':String,
  'buoi100':String,
  'buoi101':String,
  'buoi102':String,
  'buoi103':String,
  'buoi104':String,
  'buoi105':String,
  'buoi106':String,
  'buoi107':String,
  'buoi108':String,
  'buoi109':String,
  'buoi110':String,
  'buoi111':String,
  'buoi112':String,
  'buoi113':String,
  'buoi114':String,
  'buoi115':String,
  'buoi116':String,
  'buoi117':String,
  'buoi118':String,
  'buoi119':String,
  'buoi120':String,
  'buoi121':String,
  'buoi122':String,
  'buoi123':String,
  'buoi124':String,
  'buoi125':String,
  'buoi126':String,
  'buoi127':String,
  'buoi128':String,
  'buoi129':String,
  'buoi130':String,
  'buoi131':String,
  'buoi132':String,
  'buoi133':String,
  'buoi134':String,
  'buoi135':String,
  'buoi136':String,
  'buoi137':String,
  'buoi138':String,
  'buoi139':String,
  'buoi140':String,
  'buoi141':String,
  'buoi142':String,
  'buoi143':String,
  'buoi144':String,
  'buoi145':String,
  'buoi146':String,
  'buoi147':String,
  'buoi148':String,
  'buoi149':String,
  'buoi150':String,
  'buoi151':String,
  'buoi152':String,
  'buoi153':String,
  'buoi154':String,
  'buoi155':String,
  'buoi156':String,
  'buoi157':String,
  // 'buoihoc1':String,
  // 'buoihoc2':String,
  // 'buoihoc3':String,
  // 'buoihoc4':String,
  // 'buoihoc5':String,
  // 'buoihoc6':String,
  // 'buoihoc7':String,
  // 'buoihoc8':String,
  // 'buoihoc9':String,
  // 'buoihoc10':String,
  // 'buoihoc11':String,
  // 'buoihoc12':String,
  // 'buoihoc13':String,
  // 'buoihoc14':String,
  // 'buoihoc15':String,
  // 'buoihoc16':String,
  // 'buoihoc17':String,
  // 'buoihoc18':String,
  // 'buoihoc19':String,
  // 'buoihoc20':String,
  // 'buoihoc21':String,
  // 'buoihoc22':String,
  // 'buoihoc23':String,
  // 'buoihoc24':String,
  // 'buoihoc25':String,
  // 'buoihoc26':String,
  // 'buoihoc27':String,
  // 'buoihoc28':String,
  // 'buoihoc29':String,
  // 'buoihoc30':String,
  // 'buoihoc31':String,
  // 'buoihoc32':String,
  // 'buoihoc33':String,
  // 'buoihoc34':String,
  // 'buoihoc35':String,
  // 'buoihoc36':String,
  // 'buoihoc37':String,
  // 'buoihoc38':String,
  // 'buoihoc39':String,
  // 'buoihoc40':String,
  // 'buoihoc41':String,
  // 'buoihoc42':String,
  // 'buoihoc43':String,
  // 'buoihoc44':String,
  // 'buoihoc45':String,
  // 'buoihoc46':String,
  // 'buoihoc47':String,
  // 'buoihoc48':String,
  // 'buoihoc49':String,
  // 'buoihoc50':String,
  // 'buoihoc51':String,
  // 'buoihoc52':String,
  // 'buoihoc53':String,
  // 'buoihoc54':String,
  // 'buoihoc55':String,
  // 'buoihoc56':String,
  // 'buoihoc57':String,
  // 'buoihoc58':String,
  // 'buoihoc59':String,
  // 'buoihoc60':String,
  // 'buoihoc61':String,
  // 'buoihoc62':String,
  // 'buoihoc63':String,
  // 'buoihoc64':String,
  // 'buoihoc65':String,
  // 'buoihoc66':String,
  // 'buoihoc67':String,
  // 'buoihoc68':String,
  // 'buoihoc69':String,
  // 'buoihoc70':String,
  // 'buoihoc71':String,
  // 'buoihoc72':String,
  // 'buoihoc73':String,
  // 'buoihoc74':String,
  // 'buoihoc75':String,
  // 'buoihoc76':String,
  // 'buoihoc77':String,
  // 'buoihoc78':String,
  // 'buoihoc79':String,
  // 'buoihoc80':String,
  // 'buoihoc81':String,
  // 'buoihoc82':String,
  // 'buoihoc83':String,
  // 'buoihoc84':String,
  // 'buoihoc85':String,
  // 'buoihoc86':String,
  // 'buoihoc87':String,
  // 'buoihoc88':String,
  // 'buoihoc89':String,
  // 'buoihoc90':String,
  // 'buoihoc91':String,
  // 'buoihoc92':String,
  // 'buoihoc93':String,
  // 'buoihoc94':String,
  // 'buoihoc95':String,
  // 'buoihoc96':String,
  // 'buoihoc97':String,
  // 'buoihoc98':String,
  // 'buoihoc99':String,
  // 'buoihoc100':String,
  // 'buoihoc101':String,
  // 'buoihoc102':String,
  // 'buoihoc103':String,
  // 'buoihoc104':String,
  // 'buoihoc105':String,
  // 'buoihoc106':String,
  // 'buoihoc107':String,
  // 'buoihoc108':String,
  // 'buoihoc109':String,
  // 'buoihoc110':String,
  // 'buoihoc111':String,
  // 'buoihoc112':String,
  // 'buoihoc113':String,
  // 'buoihoc114':String,
  // 'buoihoc115':String,
  // 'buoihoc116':String,
  // 'buoihoc117':String,
  // 'buoihoc118':String,
  // 'buoihoc119':String,
  // 'buoihoc120':String,
  // 'buoihoc121':String,
  // 'buoihoc122':String,
  // 'buoihoc123':String,
  // 'buoihoc124':String,
  // 'buoihoc125':String,
  // 'buoihoc126':String,
  // 'buoihoc127':String,
  // 'buoihoc128':String,
  // 'buoihoc129':String,
  // 'buoihoc130':String,
  // 'buoihoc131':String,
  // 'buoihoc132':String,
  // 'buoihoc133':String,
  // 'buoihoc134':String,
  // 'buoihoc135':String,
  // 'buoihoc136':String,
  // 'buoihoc137':String,
  // 'buoihoc138':String,
  // 'buoihoc139':String,
  // 'buoihoc140':String,
  // 'buoihoc141':String,
  // 'buoihoc142':String,
  // 'buoihoc143':String,
  // 'buoihoc144':String,
  // 'buoihoc145':String,
  // 'buoihoc146':String,
  // 'buoihoc147':String,
  // 'buoihoc148':String,
  // 'buoihoc149':String,
  // 'buoihoc150':String,
  // 'buoihoc151':String,
  // 'buoihoc152':String,
  // 'buoihoc153':String,
  // 'buoihoc154':String,
  // 'buoihoc155':String,
  // 'buoihoc156':String,
  // 'buoihoc157':String,
  'timemin': String,
  'timemax': String
})
module.exports=mongoose.model('teachers',teacher)